### ISSUE TITLE
Improve appstream metainfo

### ISSUE THREAD

**Issue by bertob** [diamondburned/dissent#262]
This app's app store listing has a lot of potential, but there are a bunch of smaller papercuts:

- Summary is longer than 35 characters #249
- Screenshots with non-default window controls (should be close-only)
- The description `GTK4 Discord client in Go` is a bit short, it'd be nicer to at least have a full sentence listing the most important features (or in this case maybe also which Discord features are not supported yet)
- No release notes (at least not in GNOME Software)
- Flathub verification #261

**Comment by diamondburned** [comment]
Tracking comment:

* [ ] Summary is longer than 35 characters [Better appdata summary #249](https://github.com/diamondburned/dissent/issues/249)
* [ ] Screenshots with non-default window controls (should be close-only) [Screenshots should use default settings #228](https://github.com/diamondburned/dissent/issues/228)
* [ ] The description `GTK4 Discord client in Go` is a bit short, it'd be nicer to at least have a full sentence listing the most important features (or in this case maybe also which Discord features are not supported yet)
* [ ] No release notes (at least not in GNOME Software)
* [ ] Flathub verification [Flathub Verification #261](https://github.com/diamondburned/dissent/issues/261)
* [ ] Brand colors

**Comment by diamondburned** [comment]
Where does the brand color go? Are they more for the UI or for the metadata?

**Comment by bertob** [comment]
Opened a PR for brand colors, for context, this is what that's about: https://docs.flathub.org/blog/introducing-app-brand-colors

**Comment by tfuxu** [comment]
Nice, we are now failing only "Default settings" check in Flathub:
![Screenshot 2024-04-07 at 16-27-59 Install Dissent on Linux Flathub](https://github.com/diamondburned/dissent/assets/73042332/c47d4d85-2219-4884-9f60-13a9989f6a62)
